// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAehjOVma5o0F5LkZs2G1T-_oX9BDfV5aA',
    appId: '1:1058153867300:web:9fc73b87e39216aaaa90b1',
    messagingSenderId: '1058153867300',
    projectId: 'beggar-king-e20eb',
    authDomain: 'beggar-king-e20eb.firebaseapp.com',
    storageBucket: 'beggar-king-e20eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJNTp2gT_Vaz91Gzgoh4eLEOXnkusYRRM',
    appId: '1:1058153867300:android:725a1b7f8c3f9d9faa90b1',
    messagingSenderId: '1058153867300',
    projectId: 'beggar-king-e20eb',
    storageBucket: 'beggar-king-e20eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDj7nF-PJic58p1IkK4B-uQqtqIyXR0uFE',
    appId: '1:1058153867300:ios:f0e93f6fe63b3876aa90b1',
    messagingSenderId: '1058153867300',
    projectId: 'beggar-king-e20eb',
    storageBucket: 'beggar-king-e20eb.appspot.com',
    iosBundleId: 'com.example.beggarking',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDj7nF-PJic58p1IkK4B-uQqtqIyXR0uFE',
    appId: '1:1058153867300:ios:7c4f07357da43339aa90b1',
    messagingSenderId: '1058153867300',
    projectId: 'beggar-king-e20eb',
    storageBucket: 'beggar-king-e20eb.appspot.com',
    iosBundleId: 'com.example.beggarking.RunnerTests',
  );
}
